import React, { useState } from "react";
import { 
  GraphNode, 
  GraphEdge, 
  UserRole 
} from "../../types";
import { apiClient } from "../../utils/apiClient";
import { 
  FileText, 
  Sparkles, 
  Download, 
  Printer, 
  Copy, 
  Check, 
  ShieldCheck, 
  Clock, 
  Share2, 
  RefreshCw,
  Award
} from "lucide-react";
import ReactMarkdown from "react-markdown";

interface ReportGeneratorProps {
  nodes: GraphNode[];
  edges: GraphEdge[];
  userRole: UserRole;
  onAuditLog: (action: string, target: string, justification: string) => void;
}

export const ReportGenerator: React.FC<ReportGeneratorProps> = ({
  nodes,
  edges,
  userRole,
  onAuditLog,
}) => {
  const [reportType, setReportType] = useState("EXECUTIVE_THREAT_DOSSIER");
  const [targetEntity, setTargetEntity] = useState("Operation Shadow Viper");
  const [timeframe, setTimeframe] = useState("Past 30 Days (High Priority)");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedReport, setGeneratedReport] = useState<string>(`# OSINT INTELLIGENCE ASSESSMENT & TARGET DOSSIER
**Operation:** Operation Shadow Viper (APT-29 Auxiliary)  
**Classification:** SECRET // NOFORN  
**Report ID:** RPT-2026-AEGIS-0941  
**Generated By:** Lead OSINT Intelligence Officer (${userRole.toUpperCase()})  
**Verification Hash:** \`e7f1092a838bc8d91029c01928374a5f6e7d8c9b\`  

---

### 1. Executive Summary
A comprehensive cross-correlation of network telemetry, darknet chatter, and personnel vetting data reveals an ongoing coordinated reconnaissance campaign targeting **SCIF Delta Gateway Server 01**. Discovered node linkages indicate that the adversary has established persistent C2 infrastructure over encrypted VPN tunnels and crypto mixers to facilitate data exfiltration.

### 2. High-Risk Node Linkages Identified
* **Victor 'Viper' Vance (Target ID: node-1)**: Risk Score **88/100**. Observed after-hours physical badge swipes at SCIF Facility Delta correlating with anomalous high-volume outbound network bursts.
* **194.26.29.11 (C2 IP: node-3)**: Risk Score **94/100**. Confirmed Tor exit relay node executing port scans against corporate DMZ.
* **0x71C...b829 (Mixer Wallet: node-5)**: Risk Score **89/100**. 14.5 ETH transferred from sanction-flagged offshore entity **Vance Aerospace & Defense Holdings LLC**.

### 3. Attack Surface & Defensive Posture Analysis
Red Team vulnerability assessments show an exposure score of **64/100**. The primary lateral attack path leverages unpatched RPC listeners (CVE-2026-3809) coupled with compromised Master Key credentials.

### 4. Prescribed Strategic Mitigations
1. **Immediate Revocation**: Enforce emergency hardware token quarantine on Master Key \`KEY-SCIF-001\`.
2. **Perimeter Firewall Rule**: Drop all ingress and egress packets matching ASN 48290 (194.26.29.11).
3. **Quorum Escalation**: Require 2-of-3 multi-custody signatures for any privilege escalation on SCIF Delta Gateway.

---
*Verified by Aegis Defense Cryptographic Chain Engine.*`);

  const [copied, setCopied] = useState(false);

  const handleGenerateReport = async () => {
    setIsGenerating(true);
    try {
      const res = await apiClient.post("/api/generate-report", {
        nodes,
        edges,
        reportType,
        targetFocus: targetEntity,
      });
      const data = res.data;
      if (data.report) {
        setGeneratedReport(data.report);
      }
      onAuditLog(
        "AUTOMATED_OSINT_REPORT_GENERATED",
        `Type: ${reportType} (${targetEntity})`,
        "Generated automated AI intelligence brief for executive dissemination."
      );
    } catch (e) {
      console.error(e);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedReport);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([generatedReport], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Aegis-OSINT-Dossier-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    a.remove();
  };

  return (
    <div className="flex-1 flex flex-col h-full bg-slate-950 overflow-hidden p-5 space-y-5">
      {/* Header & Parameters */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-5 shadow-lg space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 pb-3">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 rounded-xl bg-cyan-500/20 border border-cyan-500/30 flex items-center justify-center">
              <FileText className="w-5 h-5 text-cyan-400" />
            </div>
            <div>
              <h2 className="text-base font-bold text-slate-100 font-mono uppercase">
                AUTOMATED OSINT DOSSIER & COMPLIANCE REPORT GENERATOR
              </h2>
              <p className="text-xs text-slate-400">
                AI-synthesized threat dossiers cross-referencing {nodes.length} graph entities and {edges.length} active links
              </p>
            </div>
          </div>

          <button
            onClick={handleGenerateReport}
            disabled={isGenerating}
            className="px-4 py-2 bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white rounded-xl font-mono font-bold text-xs flex items-center space-x-2 shadow-lg shadow-cyan-950/40 disabled:opacity-50 cursor-pointer transition-all"
          >
            <Sparkles className={`w-4 h-4 text-cyan-200 ${isGenerating ? "animate-spin" : ""}`} />
            <span>{isGenerating ? "SYNTHESIZING INTELLIGENCE BRIEF..." : "GENERATE AI DOSSIER"}</span>
          </button>
        </div>

        {/* Configuration Parameters */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
          <div>
            <label className="text-[10px] font-mono uppercase text-slate-400 block mb-1">
              REPORT TEMPLATE
            </label>
            <select
              value={reportType}
              onChange={(e) => setReportType(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2 text-slate-200 font-mono focus:outline-none focus:border-cyan-500"
            >
              <option value="EXECUTIVE_THREAT_DOSSIER">Executive OSINT Threat Dossier</option>
              <option value="RED_TEAM_GAP_ASSESSMENT">Red Team Offensive & Defense Gap Report</option>
              <option value="PERSONNEL_VETTING_AUDIT">Personnel Security Clearance & Vetting Brief</option>
              <option value="CTI_IOC_EXFILTRATION_MATRIX">CTI Technical Indicator & Lateral Hop Matrix</option>
            </select>
          </div>

          <div>
            <label className="text-[10px] font-mono uppercase text-slate-400 block mb-1">
              TARGET ENTITY FOCUS
            </label>
            <input
              type="text"
              value={targetEntity}
              onChange={(e) => setTargetEntity(e.target.value)}
              placeholder="e.g. Operation Shadow Viper or Victor Vance"
              className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2 text-slate-200 font-mono focus:outline-none focus:border-cyan-500"
            />
          </div>

          <div>
            <label className="text-[10px] font-mono uppercase text-slate-400 block mb-1">
              TELEMETRY TIMEFRAME
            </label>
            <select
              value={timeframe}
              onChange={(e) => setTimeframe(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2 text-slate-200 font-mono focus:outline-none focus:border-cyan-500"
            >
              <option value="Past 24 Hours (Active Incident)">Past 24 Hours (Active Incident)</option>
              <option value="Past 30 Days (High Priority)">Past 30 Days (High Priority)</option>
              <option value="Full Historical Case Archive">Full Historical Case Archive</option>
            </select>
          </div>
        </div>
      </div>

      {/* Rendered Dossier Document View */}
      <div className="flex-1 bg-slate-900/90 border border-slate-800 rounded-2xl shadow-xl overflow-hidden flex flex-col">
        {/* Document Action Ribbon */}
        <div className="p-3 border-b border-slate-800 bg-slate-950/80 flex items-center justify-between text-xs font-mono">
          <div className="flex items-center space-x-2 text-slate-300">
            <Award className="w-4 h-4 text-cyan-400" />
            <span className="font-bold uppercase text-slate-100">CLASSIFIED DOCUMENT PREVIEW</span>
            <span className="text-slate-500">|</span>
            <span className="text-slate-400">STATUS: READY FOR EXPORT</span>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handleCopy}
              className="px-2.5 py-1 bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 rounded-lg flex items-center space-x-1 transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? "COPIED" : "COPY MARKDOWN"}</span>
            </button>

            <button
              onClick={handleDownload}
              className="px-2.5 py-1 bg-cyan-600 hover:bg-cyan-500 text-white rounded-lg flex items-center space-x-1 shadow-sm transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              <span>EXPORT .MD</span>
            </button>
          </div>
        </div>

        {/* Markdown Dossier Container */}
        <div className="flex-1 overflow-y-auto p-8 prose prose-invert max-w-none prose-headings:text-slate-100 prose-p:text-slate-300 prose-strong:text-cyan-300 prose-code:text-cyan-400 prose-code:bg-slate-950 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-code:border prose-code:border-slate-800 text-sm leading-relaxed">
          <ReactMarkdown>{generatedReport}</ReactMarkdown>
        </div>
      </div>
    </div>
  );
};
